Rails.application.routes.draw do
  post '/feedback' => 'home#feedback'
  post 'survey/response' => 'home#survey_response'
  get '/about-us' => 'home#about'
  get '/features' => 'home#features'
  get '/ad-tube' => 'home#ad_tube'
  get 'signin' => 'home#signin'
  get 'signout' => 'home#signout'
  get '/ads/sample' => 'home#ads_sample'
  get '/ads/survey' => 'home#ads_survey'
  get 'search/yahoo' => 'home#search_yahoo'
  get 'search/a2ma' => 'home#search_a2ma'
  get 'search/results/a2ma' => 'home#search_results_a2ma'
  get 'search/google' => 'home#search_google'
  root 'home#welcome'
end
